"""empty message

Revision ID: 33234c9dda92
Revises:
Create Date: 2020-08-19 15:31:44.347394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33234c9dda92"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "climb",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=True),
        sa.Column("city", sa.String(length=160), nullable=True),
        sa.Column("province", sa.String(length=160), nullable=True),
        sa.Column("cotacol_points", sa.SmallInteger(), nullable=True),
        sa.Column("distance", sa.SmallInteger(), nullable=True),
        sa.Column("elevation_diff", sa.SmallInteger(), nullable=True),
        sa.Column("avg_grade", sa.Float(precision=3), nullable=True),
        sa.Column("gpx_points", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("date_joined", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "social_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("uid", sa.String(length=191), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_account")
    op.drop_table("user")
    op.drop_table("climb")
    # ### end Alembic commands ###
