"""empty message

Revision ID: 6f7910d5dab9
Revises: 33234c9dda92
Create Date: 2020-08-20 21:06:32.422592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f7910d5dab9"
down_revision = "33234c9dda92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("climb", sa.Column("extra_data", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("extra_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "extra_data")
    op.drop_column("climb", "extra_data")
    # ### end Alembic commands ###
